#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to store the images
# NOCACHE: set this to "--no-cache" to turn off the Docker build cache
#
# NOTE: to run this you MUST set the REGISTRY environment variable to
# your own image registry/namespace otherwise the `docker push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.

set -ex
export REGISTRY="icr.io/devel"
#export REGISTRY=${REGISTRY:-icr.io/codeengine}


# Build the image
docker build ${NOCACHE} -t ${REGISTRY}/alpine-node-express:latest . --arch amd64
#podman build -t alpine-node-express-base:1.0 . --arch amd64
#podman build --no-cache -t alpine-node-express-base:1.0 . --arch arm64

# And push it
docker push ${REGISTRY}/alpine-node-express-base:latest
#podman push ${REGISTRY}/alpine-node-express-base
